name: deploy_to_railway

on:
  workflow_run:
    workflows: ["cgg-model-training"] # Ensure this workflow runs only after the training workflow is completed.
    types:
      - completed

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Deploy to Railway
        env:
          RAILWAY_API_TOKEN: ${{ secrets.RAILWAY_API_TOKEN }}
          RAILWAY_PROJECT_ID: ${{ secrets.RAILWAY_PROJECT_ID }}
        run: |
          # Authenticate with Railway
          railway authenticate $RAILWAY_API_TOKEN
          
          # Deploy to Railway
          railway up

