name: cgg-model-training
on: [push]
jobs:
  run:
    runs-on: [ubuntu-latest]
    #container: docker://dvcorg/cml-py3:latest
    steps:
      - uses: actions/checkout@v2
      - name: 'Train my model'
        env:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
        run: |

          # Your ML workflow goes here
          pip install -r requirements.txt
          python scripts/ml_train.py


      - name: Configure Git
        run: |
          git config --global user.email "ajaymathew522@gmail.com"
          git config --global user.name "ajay"

      - name: Commit and Push Model
        run: |
          git add CNN_model.keras
          git commit -m "Add CNN_model.keras"
          git push
