name: cgg-model-training
on: [push]
jobs:
  run:
    runs-on: [ubuntu-latest]
    #container: docker://dvcorg/cml-py3:latest
    steps:
      - uses: actions/checkout@v2
      - name: 'Train my model'
        env:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
        run: |

          # Your ML workflow goes here
          pip install -r requirements.txt
          python scripts/ml_train.py


      - name: Configure Git and Push Model
        run: |
          git config --global user.email "ajaymathew522@gmail.com"
          git config --global user.name "ajay"
          git remote set-url origin https://github.com/${{ github.repository }}.git
          git add CNN_model.keras
          git commit -m "Add CNN_model.keras"
          git push --set-upstream origin ${{ github.ref }}
        env:
          GH_PAT: ${{ secrets.GH_PAT }}          
      
